# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: 

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'custom'
#    custom: 'tool'
#    arguments: 'restore'
#
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'custom'
#    custom: 'cake'
#    arguments: 'build.cake'
    
- task: PowerShell@2
  inputs:
    filePath: 'build.ps1'
